### ISSUE TITLE
Unable to generate project

### ISSUE THREAD

**Issue by Davis-A** [splashkit/skm#13]
Platform Linux

So i'm trying to play around with splashkit.

It's installed.  When i run
`$skm`
It just opens up window of the splashkit site.

If i try the commands according to the readme.md

eg 
`$skm create -l pascal -n helloWorld`
Output:

> error: build is not a valid command.

`$skm init`
It gives me an option of cpp or pascal, then what to name it.  No matter what i choose it prompts me that it was successful and that a splashkit project has been created in my current working directory of that name.  However nothing actually happens.

**Comment by macite** [comment]
The documentation was very out of date - I've updated that to include the new process for using skm.
