### ISSUE TITLE
No License.

### ISSUE THREAD

**Issue by monoxane** [splashkit/skm#31]
This repository is aimed at beginners but does not have a license file in it, a lack of license is legally implicit absolute copyright for all content by its original authors which results in literally everyone forking or cloning this code to be in violation of the copyright law of the US (GitHub and the code location), and Australia (Organization location and presumed majority of the users).

Please rectify this or a number of people will be unable to continue coursework from the university.

**Comment by bonexd** [comment]
ive already proposed a license as a pull request dipshit ﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽

**Comment by monoxane** [comment]
Please also be aware that for the new license to be valid everyone who has contributed code to this (And the other repositories) has to give explicit permission that they are now licensing contributed code under the new GPL-3.0 license, the same as if a repo were to change between different open source licenses.

**Comment by ghost** [comment]
This also retroactively affects everyone. Without a license, any contributor can now make the case that you are distributing their work illegally.

**Comment by gill6151** [comment]
ligma
